name: dartgenerate
description: An inline generator collection for Dart.
version: 2.3.0
homepage: https://github.com/ajinasokan/dartgen

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^8.1.1
  watcher: ^1.1.0
  dart_style: ^3.0.1
  strings: ^4.0.1
  slugify: ^2.0.0
  glob: ^2.1.1
  path: ^1.8.3
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.2

executables:
  dartgenerate: main
